
name: Deploy to Azure Web App

on:
  push:
    branches:
      - main  # or your default branch

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
              with:
          python-version: '3.11'

    - name: Install dependencies
      run: |
        pip install -r requirements.txt

    # Add any other necessary steps like linting, testing, etc.

    - name: 'Deploy to Azure Web App'
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'YourAppName' # Replace with your app name
        slot-name: 'production' # Optional
        publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }} # Set in GitHub secrets
        package: .
